export const lmsCategories = [
  "Web Development",
  "Data Science",
  "UI/UX Design",
  "Mobile Development",
  "Business",
];

export const lmsCourses = [
  {
    id: "c1",
    title: "The Complete 2026 Web Development Bootcamp",
    instructor: "Dr. Angela Yu",
    rating: 4.8,
    reviews: 120500,
    price: 89.99,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop",
    category: "Web Development",
    level: "Beginner",
    duration: "65 hours",
  },
  {
    id: "c2",
    title: "UI/UX Design Masterclass: From Beginner to Pro",
    instructor: "Gary Simon",
    rating: 4.9,
    reviews: 45200,
    price: 94.99,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop",
    category: "UI/UX Design",
    level: "All Levels",
    duration: "24 hours",
  },
  {
    id: "c3",
    title: "Machine Learning A-Z: AI, Python & R",
    instructor: "Kirill Eremenko",
    rating: 4.7,
    reviews: 88400,
    price: 109.99,
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee57d5?w=600&h=400&fit=crop",
    category: "Data Science",
    level: "Intermediate",
    duration: "42 hours",
  },
  {
    id: "c4",
    title: "Next.js 15 & React - The Complete Guide",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.8,
    reviews: 32100,
    price: 84.99,
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=400&fit=crop",
    category: "Web Development",
    level: "Intermediate",
    duration: "32 hours",
  },
  {
    id: "c5",
    title: "Flutter & Dart - The Complete Guide",
    instructor: "Academind",
    rating: 4.6,
    reviews: 54000,
    price: 79.99,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=400&fit=crop",
    category: "Mobile Development",
    level: "Beginner",
    duration: "41 hours",
  },
  {
    id: "c6",
    title: "Digital Marketing Masterclass",
    instructor: "Phil Ebiner",
    rating: 4.5,
    reviews: 67000,
    price: 69.99,
    image: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=400&fit=crop",
    category: "Business",
    level: "Beginner",
    duration: "35 hours",
  },
];

export const lmsEnrolledCourses = [
  {
    courseId: "c1",
    course: lmsCourses[0],
    progress: 45,
    lastAccessed: "2 days ago",
  },
  {
    courseId: "c2",
    course: lmsCourses[1],
    progress: 80,
    lastAccessed: "Today",
  },
  {
    courseId: "c4",
    course: lmsCourses[3],
    progress: 12,
    lastAccessed: "1 week ago",
  },
];

export const lmsUser = {
  name: "Joshua Student",
  email: "joshua@example.com",
  avatar: "https://ui-avatars.com/api/?name=Joshua+Student&background=6d28d9&color=fff",
  joinDate: "January 2026",
  hoursLearned: 142,
  certificates: 3,
};
